### ISSUE TITLE
Look at search datamodel using to much documents

### ISSUE THREAD

**Issue by runes83** [unipluss/invoicetransactions#4]
I've imported about 1000 transactions and it's already at 30% over 1 000 000 documents.

One alternative could be to recreate the search indexes every night with accumulations from tablestorage, and during the day add the incoming transactions to get more realtime overview.

**Comment by runes83** [comment]
The basic plan [Azure Search](https://azure.microsoft.com/nb-no/pricing/details/search/) is 1m Documents and that should be sufficient with some adjustments.

Our usage is 2k-4k transactions pr year.
But if we have 1-200 accounts, with 5-10 products for 12 months a year that could keep us going much longer.

**Comment by siimav** [comment]
After importing 1000 transactions there were 300 000 items in search index? Is it a bug or is the Amount value for each transaction somewhere around 300?

**Comment by runes83** [comment]
The 1000 transactions where sums pr customer pr month, pr year some of them where 300 some 3000 and some 9. But I think we have to look if it's possible to put aggregated sums into the search service in order to maximize the return.

1 alternative could be to write incoming transactions to tablestorage and search as now, and each night rebuild search from tablestorage with aggredated sums (pr customer, pr product pr month pr year) for example. That would result in much less data in search but still be able to sum by month product and so on.

**Comment by siimav** [comment]
That would require completely reworking how data is queried for stats methods. Currently we are using search facets for getting aggregations and that is only possible when each transaction is indexed as a separate document.
It's possible to create a hybrid solution where transactions older than a couple of months are removed from index and some kind of aggregated-total items are added insted. But that would require querying from 2 separate indexes (latest transaction items + aggregated totals) to get the correct totals.
Or just rely on nightly updates to the aggregations index and keep transaction items only in table storage?

**Comment by runes83** [comment]
I'll discuss this with my colleague and get back to on this, but if we want to throw many transaction into this solution without paying for many search service partitions with preimum price we have to do something about it.

**Comment by runes83** [comment]
@siimav @steinolav 
One solution could be to have 2 indexes, history and currentmonth.
Currentmonth could contain single transactions (as today solution) and history could contain past months and year. Totals could be calculated by summing these two indexes.
It could also be smart to have a table in table storage that have totals pr product, customer, month and year. In case search have to rebuilt one do not have to reindex the entire table.

**Comment by siimav** [comment]
@steinolav @runes83 
I'm trying to think of the benefits of keeping 2 indexes. The only thing I could come up with, is that new transactions are almost immediately (delay usually <1min) reflected in the statistics results. When using only the monthly totals index, the results would be updated once a day.  Is "almost-always-up-to-date" statistics important to you or is there another reason I didn't think of? 
On the other hand, maintaining and querying from 2 separate indexes adds extra complexity. It sounds like 1-2 days of extra work.

Keeping a copy of the monthly totals search index in table store sounds reasonable. It doesn't look too difficult and should only be maybe half a day of work.

**Comment by runes83** [comment]
The reason to have "almost-alsways-up-to-date" statistics is that we use that to determine load on the system and act accordingly.

**Comment by runes83** [comment]
@siimav If we choose both that will be 1,5-2,5 days work ?

**Comment by siimav** [comment]
Yes, probably closer to 2.5 I think.

I'm guessing we should also slightly change the model of how transactions are stored in search index. Currently it is only possbile to query results that fall into a specific month. So we should add the actual dates of when the transactions were submitted to the API. This would allow to query daily, hourly or even more precise statistics for determining the load.

Also, for how long would the individual transactions be kept in the search index? 31 days? So in queries anything older than 31 days would come from the monthly totals index and anything newer from the individual transaction index.

**Comment by runes83** [comment]
Table storage query beyond Partition / RowKey are very heavy operations, so it could be effective to have the months totalt in search or in memory/cache to query.

**Comment by siimav** [comment]
@steinolav @runes83
Not sure what you mean by that last reply. I thought we already decided a couple of posts ago that monthly totals are kept in the search index for querying? And also you would like to keep a copy of the totals index inside table storage so that rebuilding the search index would be faster.

**Comment by runes83** [comment]
Forget the last reply I think we are covered by your solution.

**Comment by siimav** [comment]
@steinolav @runes83
This change should now be ready for testing. I have implemented both the totals index updating/querying as well as rebuilding totals index from table storage.
Deploying this requires that you delete the previous search index and 'transactions' table. There were a couple of metadata fields added that require re-filling both with new data.
Also a webjob scheduler is needed for UpdateTotals job because it needs to run daily. The scheduled time should be something after 00:00 UTC, like 00:05 to ensure that all the transactions from the previous day have been committed to table storage.
If all transactions are added through the Transactions controller POST method, then no further actions are needed. But if you add transactions directly to table storage, a re-indexing is required for all of those that are with a date outside the 31-day automatic re-index period. This can be done by adding a entity for each re-indexable month to the 'reindexabletransactions' table and running the 'UpdateTotals' webjob. Currently there's no API method for achieving that and operations to the table storage must be done with Visual Studio Cloud Explorer or something similar.
